name: Gemini AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Gemini AI Code Review
        uses: truongnh1992/gemini-ai-code-reviewer@v9.2.1
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_MODEL: gemini-2.5-flash  # 可选，默认 gemini-2.5-flash
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
